import { Inter } from "next/font/google";
// Josefin Sans
import { Josefin_Sans } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/project/Navbar";
import Header from "@/components/project/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/project/Footer";

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-darkTextBlue ${josefinSans.className}`}>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
